version: '2.4'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: amisno
    ports:
      - 27017:27017
  amisno-config-server:
    image: fourmipanda/amisno-config-server:latest
    expose:
      - 9101
    ports:
      - 9101:9101
    healthcheck:
      test: curl -v --silent http://amisno-config-server:9101/actuator/health 2>&1 | grep UP
      timeout: 5s
      interval: 5s
      retries: 10
  amisno-infra-eureka:
    image: fourmipanda/amisno-infra-eureka:latest
    expose:
      - 9103
    ports:
      - 9103:9103
    healthcheck:
      test: curl -v --silent http://amisno-infra-eureka:9103/actuator/health 2>&1 | grep UP
      timeout: 5s
      interval: 5s
      retries: 10
    depends_on:
      amisno-config-server:
        condition: service_healthy
  amisno-cloud-gateway:
    image: fourmipanda/amisno-cloud-gateway:latest
    expose:
      - 9102
    ports:
      - 9102:9102
    healthcheck:
      test: curl -v --silent http://amisno-cloud-gateway:9102/actuator/health 2>&1 | grep UP
      timeout: 5s
      interval: 5s
      retries: 10
    depends_on:
      amisno-infra-eureka:
        condition: service_healthy
      amisno-config-server:
        condition: service_healthy
  amisno-order-service:
    image: fourmipanda/amisno-order-service:latest
    expose:
      - 8082
    ports:
      - 8082:8082
    depends_on:
      amisno-infra-eureka:
        condition: service_healthy
      amisno-config-server:
        condition: service_healthy
  amisno-catalog-service:
    image: fourmipanda/amisno-catalog-service:latest
    expose:
      - 8090
    depends_on:
      amisno-infra-eureka:
        condition: service_healthy
      amisno-config-server:
        condition: service_healthy
  amisno-catalog-service2:
    image: fourmipanda/amisno-catalog-service:latest
    expose:
      - 8090
    depends_on:
      amisno-infra-eureka:
        condition: service_healthy
      amisno-config-server:
        condition: service_healthy