version: '2.4'
services:
  amisno-cloud-gateway:
    image: fourmipanda/amisno-cloud-gateway:1.0.0
    expose:
      - 8080
    ports:
      - 9000:8080
  amisno-order-service:
    image: fourmipanda/amisno-order-service:latest
    expose:
      - 8081
    ports:
      - 8080:8081
